Sensato.GenerateCSharp/Controllers/ContextController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Windows;
using Sensato.GenerateCSharp.Models;
using Sensato.GenerateCSharp.GlobalCode;

namespace Sensato.GenerateCSharp.Controllers
{
    public class ContextController : BaseController
    {
        // GET: Context
        public ActionResult Index(int ID_Project)
        {
            ViewBag.CurrentProject = ID_Project;
            Tb_Projects proj = db.Tb_Projects.Find(ID_Project);
            ViewBag.CurrentName = proj.ProjectName;
            var tb_Contexts = db.Tb_Contexts.Include(t => t.Tb_Projects);
            return View(tb_Contexts.Where(x=>x.ID_Project == ID_Project).ToList());
        }

        // GET: Context/Create
        public ActionResult Create(int ID_Project)
        {
            ViewBag.idProject = ID_Project;
            Tb_Projects tb = db.Tb_Projects.Find(ID_Project);
            ViewBag.CurrentName = tb.ProjectName;
            return View();
        }

        // POST: Context/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Context,ID_Project,ContextName,CreationDate")] Tb_Contexts tb_Contexts, int ID_Project)
        {
            if (ModelState.IsValid)
            {
                using (DbContextTransaction transaction = db.Database.BeginTransaction())
                {
                    try
                    {
                        db.Tb_Contexts.Add(tb_Contexts);
                        tb_Contexts.ID_Project = ID_Project;
                        tb_Contexts.CreationDate = DateTime.Now.Date;
                        db.SaveChanges();
                        transaction.Commit();
                        return RedirectToAction("Index",new { ID_Project = ID_Project });
                    }
                    catch(Exception ex)
                    {
                        transaction.Rollback();
                        MessageBox.Show("Error: " + ex.Message);
                    }
                }
                    db.Tb_Contexts.Add(tb_Contexts);
                tb_Contexts.CreationDate = DateTime.Now.Date;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_Project = new SelectList(db.Tb_Projects, "ID_Project", "ProjectName", tb_Contexts.ID_Project);
            return View(tb_Contexts);
        }

        // GET: Context/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tb_Contexts tb_Contexts = db.Tb_Contexts.Find(id);
            if (tb_Contexts == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_Project = tb_Contexts.Tb_Projects.ID_Project;
            ViewBag.CurrentName = tb_Contexts.Tb_Projects.ProjectName;
            return View(tb_Contexts);
        }

        // POST: Context/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Context,ID_Project,ContextName,CreationDate")] Tb_Contexts tb_Contexts, int ID_Project)
        {
            if (ModelState.IsValid)
            {
                using (DbContextTransaction transaction = db.Database.BeginTransaction())
                {
                    try
                    {
                        db.Entry(tb_Contexts).State = EntityState.Modified;
                        tb_Contexts.CreationDate = DateTime.Now.Date;
                        db.SaveChanges();
                        transaction.Commit();
                        return RedirectToAction("Index", new { ID_Project = ID_Project });
                    }
                    catch (Exception ex) 
                    {
                        transaction.Rollback();
                        MessageBox.Show("Error: " + ex.Message);
                    }
                }
            }
            ViewBag.ID_Project = new SelectList(db.Tb_Projects, "ID_Project", "ProjectName", tb_Contexts.ID_Project);
            return View(tb_Contexts);
        }

        // GET: Context/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tb_Contexts tb_Contexts = db.Tb_Contexts.Find(id);
            ViewBag.CurrentName = tb_Contexts.Tb_Projects.ProjectName;
            ViewBag.id_Project = tb_Contexts.Tb_Projects.ID_Project;
            if (tb_Contexts == null)
            {
                return HttpNotFound();
            }
            return View(tb_Contexts);
        }

        // POST: Context/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tb_Contexts tb_Contexts = db.Tb_Contexts.Find(id);
            if (ModelState.IsValid)
            {
                using (DbContextTransaction transaction = db.Database.BeginTransaction())
                {
                    try 
                    {
                        db.Tb_Contexts.Remove(tb_Contexts);
                        db.SaveChanges();
                        transaction.Commit();
                        return RedirectToAction("Index", new { ID_Project = tb_Contexts.ID_Project });
                    }
                    catch (Exception ex)
                    {
                        transaction.Rollback();
                        MessageBox.Show("Error: " + ex.Message);
                    }
                }
            }
            return View(tb_Contexts);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sensato.GenerateCSharp/Controllers/ObjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Windows;
using Sensato.GenerateCSharp.Models;
using Sensato.DataAccess;

namespace Sensato.GenerateCSharp.Controllers
{
    public class ObjectController : BaseController
    {
        // GET: Object
        public ActionResult Index(int idContext, int idProject)
        {
            ViewBag.idContext = idContext;
            Tb_Contexts tbC = db.Tb_Contexts.Find(idContext);
            ViewBag.CxtName = tbC.ContextName;
            ViewBag.idProject = idProject;
            var tb_Objects = db.Tb_Objects.Include(t => t.Tb_Contexts);
            return View(tb_Objects.Where(x => x.ID_Context == idContext).ToList());
        }

        // GET: Object/Create
        public ActionResult Create(int idContext, int idProject)
        {
            ViewBag.idContext = idContext;
            Tb_Contexts tb = db.Tb_Contexts.Find(idContext);
            ViewBag.CxtName = tb.ContextName;
            ViewBag.idProject = idProject;
            return View();
        }

        // POST: Object/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Object,ID_Context,ObjectName, Entity, ObjDescription, ID_AuxObject, AuxNameObject")] Tb_Objects tb_Objects, int idContext, int idProject)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    tb_Objects.ID_SysObject = tb_Objects.ID_AuxObject;
                    tb_Objects.Sys_ObjectName = tb_Objects.AuxNameObject;
                    db.Tb_Objects.Add(tb_Objects);
                    db.SaveChanges();

                    //Connection String:
                    string ConnStr;
                    Tb_Projects tb = db.Tb_Projects.Find(idProject);
                    if (tb.LocalConnection.Value)
                        ConnStr = string.Format("data source=./;initial catalog={0};integrated security=True;MultipleActiveResultSets=True;App=EntityFramework", tb.ProjectDatabase);
                    else
                        ConnStr = string.Format("data source={0};initial catalog={1};persist security info=True;user id={2};password={3};multipleactiveresultsets=True;application name=EntityFramework", tb.Server, tb.ProjectDatabase, tb.ProjectUser, tb.Password); ;

                    List<SqlParameter> queryParams = new List<SqlParameter>();
                    queryParams.Add(new SqlParameter("idObject", tb_Objects.ID_AuxObject));

                    List<Tb_Parameters> listparams = new List<Tb_Parameters>();
                    DataTable dt = DataAccessADO.GetDataTable("GetParametersFromSP",CommandType.StoredProcedure, queryParams, ConnStr, null);

                    listparams = dt.AsEnumerable().Select(x => new Tb_Parameters() {ParameterName = x.Field<string>("name"), DataType = x.Field<string>("dataT"), Length = x.Field<int>("max_length"), Presition=x.Field<int>("precision"), Nullable = x.Field<bool>("is_nullable"), IsOut = x.Field<bool>("is_output") }).ToList();

                    for(var i=0; i<listparams.Count; i++) 
                    {
                        listparams[i].ID_Object = tb_Objects.ID_Object;
                    }
                    db.Tb_Parameters.AddRange(listparams);
                    db.SaveChanges();

                    //Llamamos al metodo para almacenar los RS y las RSC
                    GetResultSet(tb_Objects.AuxNameObject, ConnStr, tb_Objects.ID_Object);
                    return RedirectToAction("Index", new {idContext = idContext, idProject = idProject});
                }
                catch(Exception ex) 
                {
                    MessageBox.Show("Error: " + ex);
                }
            }
            ViewBag.ID_Context = new SelectList(db.Tb_Contexts, "ID_Context", "ContextName", tb_Objects.ID_Context);
            return View(tb_Objects);
        }

        // GET: Object/Edit/5
        public ActionResult Edit(int? id,int idContext, int idProject)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tb_Objects tb_Objects = db.Tb_Objects.Find(id);
            if (tb_Objects == null)
            {
                return HttpNotFound();
            }
            ViewBag.idProject = idProject;
            ViewBag.idContext = idContext;
            ViewBag.CxtName = tb_Objects.Tb_Contexts.ContextName;
            return View(tb_Objects);
        }

        // POST: Object/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Object,ID_Context,ObjectName,Entity,ObjDescription,ID_AuxObject")] Tb_Objects tb_Objects, int idProject)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(tb_Objects).State = EntityState.Modified;
                    db.SaveChanges();


                    //Eliminamos de la base de datos los parametros agregados con anterioridad
                    List<Tb_Parameters> tbParameters = db.Tb_Parameters.Where(x => x.ID_Object == tb_Objects.ID_Object).ToList();
                    if (tbParameters.Count>0)
                    {
                        db.Tb_Parameters.RemoveRange(tbParameters);
                        db.SaveChanges();
                    }

                    string ConnStr;
                    Tb_Projects tb = db.Tb_Projects.Find(idProject);
                    if (tb.LocalConnection.Value)
                        ConnStr = string.Format("data source=./;initial catalog={0};integrated security=True;MultipleActiveResultSets=True;App=EntityFramework", tb.ProjectDatabase);
                    else
                        ConnStr = string.Format("data source={0};initial catalog={1};persist security info=True;user id={2};password={3};multipleactiveresultsets=True;application name=EntityFramework", tb.Server, tb.ProjectDatabase, tb.ProjectUser, tb.Password); ;

                    List<SqlParameter> queryParams = new List<SqlParameter>();
                    queryParams.Add(new SqlParameter("idObject", tb_Objects.ID_AuxObject));

                    List<Tb_Parameters> listparams = new List<Tb_Parameters>();
                    DataTable dt = DataAccessADO.GetDataTable("GetParametersFromSP", CommandType.StoredProcedure, queryParams, ConnStr, null);

                    listparams = dt.AsEnumerable().Select(x => new Tb_Parameters() { ParameterName = x.Field<string>("name"), DataType = x.Field<string>("name"), Length = x.Field<int>("max_length"), Presition = x.Field<int>("precision"), Nullable = x.Field<bool>("is_nullable"), IsOut = x.Field<bool>("is_output") }).ToList();

                    for (var i = 0; i < listparams.Count; i++)
                    {
                        listparams[i].ID_Object = tb_Objects.ID_Object;
                    }
                    db.Tb_Parameters.AddRange(listparams);
                    db.SaveChanges();

                    return RedirectToAction("Index", new { idContext = tb_Objects.ID_Context, idProject = idProject });
                }
                catch (Exception ex)
                {
                    MessageBox.Show("Error: " + ex.Message);
                }
            }
            ViewBag.ID_Context = new SelectList(db.Tb_Contexts, "ID_Context", "ContextName", tb_Objects.ID_Context);
            return View(tb_Objects);
        }

        // GET: Object/Delete/5
        public ActionResult Delete(int? id, int idContext, int idProject)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tb_Objects tb_Objects = db.Tb_Objects.Find(id);
            if (tb_Objects == null)
            {
                return HttpNotFound();
            }
            Tb_Contexts tb = db.Tb_Contexts.Find(idContext);
            ViewBag.CxtName = tb.ContextName;
            ViewBag.idProject = idProject;
            ViewBag.idContext = idContext;
            return View(tb_Objects);
        }

        // POST: Object/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int idContext, int idProject)
        {
            //List<Tb_Parameters> tbParameters = db.Tb_Parameters.Where(x => x.ID_Object == id).ToList();
            List<Tb_Parameters> tb_Parameters = new List<Tb_Parameters>();
            
            Tb_Objects tb_Objects = db.Tb_Objects.Find(id);
            if (tb_Objects.Tb_Parameters.Any())
            {
                tb_Parameters = db.Tb_Parameters.Where(x => x.ID_Object == id).ToList();
                db.Tb_Parameters.RemoveRange(tb_Parameters);
                db.SaveChanges();
            }

            db.Tb_Objects.Remove(tb_Objects);
            db.SaveChanges();
            return RedirectToAction("Index", new { idContext = idContext, idProject = idProject });
        }

        // Metodo para obtener los ID's de la tabla sysobjects
        [HttpPost]
        public JsonResult GetStoredProceduresFromSysObjects(string txt, int idProject)
        {
            string query = "GetStoredProcedures";
            Tb_Projects tb = db.Tb_Projects.Find(idProject);
            string ConnStr;
            if (tb.LocalConnection.Value)
                ConnStr = string.Format("data source=./;initial catalog={0};integrated security=True;MultipleActiveResultSets=True;App=EntityFramework", tb.ProjectDatabase);
            else

Sensato.GenerateCSharp/Controllers/ParametersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sensato.GenerateCSharp.Models;

namespace Sensato.GenerateCSharp.Controllers
{
    public class ParametersController : BaseController
    {
        // GET: Parameters
        public ActionResult Index(int idObject, int idContext, int idProject)
        {
            ViewBag.idObject = idObject;
            Tb_Objects tbO = db.Tb_Objects.Find(idObject);
            ViewBag.ObjName = tbO.ObjectName;
            ViewBag.idContext = idContext;
            ViewBag.idProject = idProject;
            var tb_Parameters = db.Tb_Parameters.Include(t => t.Tb_Objects);
            return View(tb_Parameters.Where(x=>x.ID_Object == idObject).ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sensato.GenerateCSharp/Views/Object/Create.cshtml
@model Sensato.GenerateCSharp.Models.Tb_Objects

@{
    ViewBag.Title = "Create";
}

<h2 style="color:darkslateblue;">"@ViewBag.CxtName"</h2>
<h3>Crear Objeto</h3>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID_Context, new { Value = ViewBag.idContext })
    <input type="hidden" id="ID_AuxObject" name="ID_AuxObject">
    <input type="hidden" id="AuxNameObject" name="AuxNameObject">

    <div class="form-group">
        @Html.Label("Buscar Stored Procedure", htmlAttributes: new { @class = "control-label col-md-4", @style="align: center;" })
        <div id="the-basics" class="col-md-10">
            <select id="ddObject" class="form-control selector" type="text" ></select>
        </div>
    </div>
    
    <div class="form-group">
        @Html.Label(Sensato.GenerateCSharp.GlobalCode.Resources.ObjectName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ObjectName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ObjectName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label(Sensato.GenerateCSharp.GlobalCode.Resources.ObjDescription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ObjDescription,"ObjDescription", new { htmlAttributes = new { @class = "form-control" }})
            @Html.ValidationMessageFor(model => model.ObjDescription, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label(Sensato.GenerateCSharp.GlobalCode.Resources.Entity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Entity, "Entity", new { htmlAttributes = new { @class = "form-control" }})
            @Html.ValidationMessageFor(model => model.Entity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Crear" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink(Sensato.GenerateCSharp.GlobalCode.Resources.BackToListO, "Index", new { ViewBag.idContext})
    <hr />
    <button type="button" class="btn-link" onclick="GoToContexts(@ViewBag.id_project)">@Sensato.GenerateCSharp.GlobalCode.Resources.BackToListC</button>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $('#ddObject').change(function () {
                $('#ID_AuxObject').val($(this).val());
                $('#AuxNameObject').val($('#ddObject option:selected').text());
            });
        });

        function GoToContexts(idProject) {
            window.location.href = "@Url.Action("Index", "Context")?ID_Project=" + idProject;
        }

        IDStoredProcedure = $('.selector').selectize({
            maxItems: 1,
            valueField: 'Value',
            labelField: 'Text',
            searchField: 'Text',
            create: false,
            highlight: true,
            load: function (query, callback) {
            if (!query.length) return callback();
            $.ajax({
                url: '@Url.Action("GetStoredProceduresFromSysObjects", "Object")' ,
                type: 'POST',
                dataType: 'json',
                data: {
                    txt: query,
                    idProject: '@ViewBag.idProject'
                },
                error: function (e) {
                    callback();
                },
                success: function (res) {
                    callback(res);
                    }
                });
            }
        });

</script>
}

Sensato.GenerateCSharp/Views/Object/Delete.cshtml
@model Sensato.GenerateCSharp.Models.Tb_Objects

@{
    ViewBag.Title = "Delete";
}

<h2 style="color: darkslateblue;">"@ViewBag.CxtName"</h2>
<h3>Eliminar</h3>
<h4>¿Está seguro que desea eliminar este Objeto?</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ObjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ObjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ID_SysObject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_SysObject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tb_Contexts.ContextName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tb_Contexts.ContextName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ObjDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ObjDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Entity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Entity)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-danger" /> |
            @Html.ActionLink(Sensato.GenerateCSharp.GlobalCode.Resources.BackToListO, "Index", new { ViewBag.idContext, ViewBag.idProject })
            <hr />
            <button type="button" class="btn-link" onclick="GoToIndex(@ViewBag.idProject)">@Sensato.GenerateCSharp.GlobalCode.Resources.BackToListC</button>
        </div>
    }
</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {

        });

        function GoToIndex(idProject) {
            window.location.href = "@Url.Action("Index", "Context")?ID_Project=" + idProject;
        }
    </script>
}

Sensato.GenerateCSharp/Views/Object/Edit.cshtml
@model Sensato.GenerateCSharp.Models.Tb_Objects

@{
    ViewBag.Title = "Edit";
}


<h2>"@ViewBag.CxtName"</h2>
<h3>Editar</h3>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID_Object)
    @Html.HiddenFor(model => model.ID_Context, new { Value = ViewBag.idContext })
    <input type="hidden" id="ID_AuxObject" name="ID_AuxObject">

    <div class="form-group">
        @Html.Label("Buscar Procedimiento Almacenado", htmlAttributes: new { @class = "control-label col-md-4", @style = "align: center;" })
        <div id="the-basics" class="col-md-10">
            <input id="ddObject" class="form-control selector" type="text">
        </div>
    </div>

    <div class="form-group">
        @Html.Label(Sensato.GenerateCSharp.GlobalCode.Resources.ObjectName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ObjectName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ObjectName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label(Sensato.GenerateCSharp.GlobalCode.Resources.ObjDescription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ObjDescription, "ObjDescription", new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ObjDescription, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label(Sensato.GenerateCSharp.GlobalCode.Resources.Entity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Entity, "Entity", new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Entity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-warning" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink(Sensato.GenerateCSharp.GlobalCode.Resources.BackToListO, "Index", new { ViewBag.idContext, ViewBag.idProject })
    <hr />
    <button type="button" class="btn-link" onclick="GoToContexts(@ViewBag.idProject)">@Sensato.GenerateCSharp.GlobalCode.Resources.BackToListC</button>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript">
        $(document).ready(function () {
            $('#ddObject').change(function () {
                debugger;
                $('#ID_AuxObject').val($(this).val());
            });
        });

        function GoToContexts(idProject) {
            window.location.href = "@Url.Action("Index", "Context")?ID_Project=" + idProject;
        }

        IDStoredProcedure = $('.selector').selectize({
            maxItems: 1,
            valueField: 'Value',
            labelField: 'Text',
            searchField: 'Text',
            //options: [],
            create: false,
            highlight: true,
            load: function (query, callback) {
                if (!query.length) return callback();
                $.ajax({
                url: '@Url.Action("GetStoredProceduresFromSysObjects", "Object")' ,
                type: 'POST',
                dataType: 'json',
                data: {
                    txt: query,
                    idProject: '@ViewBag.idProject'
                },
                error: function (e) {
                    callback();
                },
                success: function (res) {
                    callback(res);
                    }
                });
            }
        });

</script>
}

Sensato.GenerateCSharp/Views/Object/Index.cshtml
@model IEnumerable<Sensato.GenerateCSharp.Models.Tb_Objects>

@{
    ViewBag.Title = "Index";
}


    <h2 style="color:darkslateblue">"@ViewBag.CxtName"</h2>
<h3>Listado de Objetos</h3>
<p>
    @Html.ActionLink(Sensato.GenerateCSharp.GlobalCode.Resources.CreateNew, "Create", new {idContext = ViewBag.idContext, idProject = ViewBag.idProject }, new { @class = "btn btn-danger" })
</p>
<table class="table table-bordered">
    <tr class="bg-danger">
        <th>
            @Html.DisplayName(Sensato.GenerateCSharp.GlobalCode.Resources.SYS_ID_Object)
        </th>
        <th>
            @Html.DisplayName(Sensato.GenerateCSharp.GlobalCode.Resources.ObjectName)
        </th>
        <th>Acciones</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID_Object)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ObjectName)
            </td>
            <td>
                @Html.ActionLink(Sensato.GenerateCSharp.GlobalCode.Resources.Edit, "Edit", new { id = item.ID_Object, ViewBag.idContext, ViewBag.idProject }) |
                @Html.ActionLink(Sensato.GenerateCSharp.GlobalCode.Resources.Delete, "Delete", new { id = item.ID_Object, ViewBag.idContext, ViewBag.idProject }) |
                <button type="button" class="btn-link" onclick="ShowParameters(@item.ID_Object, @ViewBag.idContext, @ViewBag.idProject)">Ver Parámetros</button> |
                <button type="button" class="btn-link" onclick="ShowResultSets(@item.ID_Object,@ViewBag.idContext, @ViewBag.idProject)">Ver Colección de Resultados</button>
            </td>
        </tr>
    }

</table>

<div>
    <button type="button" class="btn-link" onclick="GoToIndex(@ViewBag.idProject)">@Sensato.GenerateCSharp.GlobalCode.Resources.BackToListC</button>
    <hr />
    <button type="button" class="btn-link" onclick="GoToProjects()">@Sensato.GenerateCSharp.GlobalCode.Resources.BackToListP</button>
</div>

@section scripts
    {
    <script type="text/javascript">
        $(document).ready(function () {
        });

        function GoToProjects() {
            window.location.href = "@Url.Action("Index", "Project")";
        }

        function GoToIndex(idProject) {
            window.location.href = "@Url.Action("Index", "Context")?ID_Project=" + idProject;
        }

        function ShowParameters(idObject, idContext, idProject) {
            window.location.href = "@Url.Action("Index", "Parameters")?idObject=" + idObject + "&idContext=" + idContext + "&idProject=" + idProject;
        }

        function ShowResultSets(idObject, idContext, idProject) {
            window.location.href = "@Url.Action("Index","ResultSets")?idObject=" + idObject + "&idContext=" + idContext + "&idProject=" + idProject;
        }

    </script>
}