Sensato.GenerateCSharp/Controllers/ObjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Windows;
using Sensato.GenerateCSharp.Models;
using Sensato.DataAccess;

namespace Sensato.GenerateCSharp.Controllers
{
    public class ObjectController : BaseController
    {
        // GET: Object
        public ActionResult Index(int idContext, int idProject)
        {
            ViewBag.idContext = idContext;
            Tb_Contexts tbC = db.Tb_Contexts.Find(idContext);
            ViewBag.CxtName = tbC.ContextName;
            ViewBag.idProject = idProject;
            var tb_Objects = db.Tb_Objects.Include(t => t.Tb_Contexts);
            return View(tb_Objects.Where(x => x.ID_Context == idContext).ToList());
        }

        // GET: Object/Create
        public ActionResult Create(int idContext, int idProject)
        {
            ViewBag.idContext = idContext;
            Tb_Contexts tb = db.Tb_Contexts.Find(idContext);
            ViewBag.CxtName = tb.ContextName;
            ViewBag.idProject = idProject;
            return View();
        }

        // POST: Object/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Object,ID_Context,ObjectName, Entity, ObjDescription, ID_AuxObject, AuxNameObject")] Tb_Objects tb_Objects, int idContext, int idProject)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    tb_Objects.ID_SysObject = tb_Objects.ID_AuxObject;
                    tb_Objects.Sys_ObjectName = tb_Objects.AuxNameObject;
                    db.Tb_Objects.Add(tb_Objects);
                    db.SaveChanges();

                    //Connection String:
                    string ConnStr;
                    Tb_Projects tb = db.Tb_Projects.Find(idProject);
                    if (tb.LocalConnection.Value)
                        ConnStr = string.Format("data source=./;initial catalog={0};integrated security=True;MultipleActiveResultSets=True;App=EntityFramework", tb.ProjectDatabase);
                    else
                        ConnStr = string.Format("data source={0};initial catalog={1};persist security info=True;user id={2};password={3};multipleactiveresultsets=True;application name=EntityFramework", tb.Server, tb.ProjectDatabase, tb.ProjectUser, tb.Password); ;

                    List<SqlParameter> queryParams = new List<SqlParameter>();
                    queryParams.Add(new SqlParameter("idObject", tb_Objects.ID_AuxObject));

                    List<Tb_Parameters> listparams = new List<Tb_Parameters>();
                    DataTable dt = DataAccessADO.GetDataTable("GetParametersFromSP",CommandType.StoredProcedure, queryParams, ConnStr, null);

                    listparams = dt.AsEnumerable().Select(x => new Tb_Parameters() {ParameterName = x.Field<string>("name"), DataType = x.Field<string>("dataT"), Length = x.Field<int>("max_length"), Presition=x.Field<int>("precision"), Nullable = x.Field<bool>("is_nullable"), IsOut = x.Field<bool>("is_output") }).ToList();

                    for(var i=0; i<listparams.Count; i++) 
                    {
                        listparams[i].ID_Object = tb_Objects.ID_Object;
                    }
                    db.Tb_Parameters.AddRange(listparams);
                    db.SaveChanges();

                    //Llamamos al metodo para almacenar los RS y las RSC
                    GetResultSet(tb_Objects.AuxNameObject, ConnStr, tb_Objects.ID_Object);
                    return RedirectToAction("Index", new {idContext = idContext, idProject = idProject});
                }
                catch(Exception ex) 
                {
                    MessageBox.Show("Error: " + ex);
                }
            }
            ViewBag.ID_Context = new SelectList(db.Tb_Contexts, "ID_Context", "ContextName", tb_Objects.ID_Context);
            return View(tb_Objects);
        }

        // GET: Object/Edit/5
        public ActionResult Edit(int? id,int idContext, int idProject)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tb_Objects tb_Objects = db.Tb_Objects.Find(id);
            if (tb_Objects == null)
            {
                return HttpNotFound();
            }
            ViewBag.idProject = idProject;
            ViewBag.idContext = idContext;
            ViewBag.CxtName = tb_Objects.Tb_Contexts.ContextName;
            return View(tb_Objects);
        }

        // POST: Object/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Object,ID_Context,ObjectName,Entity,ObjDescription,ID_AuxObject")] Tb_Objects tb_Objects, int idProject)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(tb_Objects).State = EntityState.Modified;
                    db.SaveChanges();


                    //Eliminamos de la base de datos los parametros agregados con anterioridad
                    List<Tb_Parameters> tbParameters = db.Tb_Parameters.Where(x => x.ID_Object == tb_Objects.ID_Object).ToList();
                    if (tbParameters.Count>0)
                    {
                        db.Tb_Parameters.RemoveRange(tbParameters);
                        db.SaveChanges();
                    }

                    string ConnStr;
                    Tb_Projects tb = db.Tb_Projects.Find(idProject);
                    if (tb.LocalConnection.Value)
                        ConnStr = string.Format("data source=./;initial catalog={0};integrated security=True;MultipleActiveResultSets=True;App=EntityFramework", tb.ProjectDatabase);
                    else
                        ConnStr = string.Format("data source={0};initial catalog={1};persist security info=True;user id={2};password={3};multipleactiveresultsets=True;application name=EntityFramework", tb.Server, tb.ProjectDatabase, tb.ProjectUser, tb.Password); ;

                    List<SqlParameter> queryParams = new List<SqlParameter>();
                    queryParams.Add(new SqlParameter("idObject", tb_Objects.ID_AuxObject));

                    List<Tb_Parameters> listparams = new List<Tb_Parameters>();
                    DataTable dt = DataAccessADO.GetDataTable("GetParametersFromSP", CommandType.StoredProcedure, queryParams, ConnStr, null);

                    listparams = dt.AsEnumerable().Select(x => new Tb_Parameters() { ParameterName = x.Field<string>("name"), DataType = x.Field<string>("name"), Length = x.Field<int>("max_length"), Presition = x.Field<int>("precision"), Nullable = x.Field<bool>("is_nullable"), IsOut = x.Field<bool>("is_output") }).ToList();

                    for (var i = 0; i < listparams.Count; i++)
                    {
                        listparams[i].ID_Object = tb_Objects.ID_Object;
                    }
                    db.Tb_Parameters.AddRange(listparams);
                    db.SaveChanges();

                    return RedirectToAction("Index", new { idContext = tb_Objects.ID_Context, idProject = idProject });
                }
                catch (Exception ex)
                {
                    MessageBox.Show("Error: " + ex.Message);
                }
            }
            ViewBag.ID_Context = new SelectList(db.Tb_Contexts, "ID_Context", "ContextName", tb_Objects.ID_Context);
            return View(tb_Objects);
        }

        // GET: Object/Delete/5
        public ActionResult Delete(int? id, int idContext, int idProject)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tb_Objects tb_Objects = db.Tb_Objects.Find(id);
            if (tb_Objects == null)
            {
                return HttpNotFound();
            }
            Tb_Contexts tb = db.Tb_Contexts.Find(idContext);
            ViewBag.CxtName = tb.ContextName;
            ViewBag.idProject = idProject;
            ViewBag.idContext = idContext;
            return View(tb_Objects);
        }

        // POST: Object/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int idContext, int idProject)
        {
            //List<Tb_Parameters> tbParameters = db.Tb_Parameters.Where(x => x.ID_Object == id).ToList();
            List<Tb_Parameters> tb_Parameters = new List<Tb_Parameters>();
            
            Tb_Objects tb_Objects = db.Tb_Objects.Find(id);
            if (tb_Objects.Tb_Parameters.Any())
            {
                tb_Parameters = db.Tb_Parameters.Where(x => x.ID_Object == id).ToList();
                db.Tb_Parameters.RemoveRange(tb_Parameters);
                db.SaveChanges();
            }

            db.Tb_Objects.Remove(tb_Objects);
            db.SaveChanges();
            return RedirectToAction("Index", new { idContext = idContext, idProject = idProject });
        }

        // Metodo para obtener los ID's de la tabla sysobjects
        [HttpPost]
        public JsonResult GetStoredProceduresFromSysObjects(string txt, int idProject)
        {
            string query = "GetStoredProcedures";
            Tb_Projects tb = db.Tb_Projects.Find(idProject);
            string ConnStr;
            if (tb.LocalConnection.Value)
                ConnStr = string.Format("data source=./;initial catalog={0};integrated security=True;MultipleActiveResultSets=True;App=EntityFramework", tb.ProjectDatabase);
            else

Sensato.GenerateCSharp/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using System.Windows;
using Sensato.GenerateCSharp.Models;

namespace Sensato.GenerateCSharp.Controllers
{
    public class ProjectController : BaseController
    {
        // GET: Project
        public ActionResult Index()
        {
            return View(db.Tb_Projects.ToList());
        }

        // GET: Project/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Project/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Project,ProjectName,FileDirectory,LocalConnection,Server,ProjectUser,ProjectDatabase,Password,CreationDate")] Tb_Projects tb_Projects)
        {
            if (ModelState.IsValid)
            {
                using (DbContextTransaction transaction = db.Database.BeginTransaction())
                {
                    try 
                    {
                        string ConnStrFormat = "";
                        if (tb_Projects.LocalConnection.Value)
                            ConnStrFormat = string.Format("data source=./;initial catalog={0};integrated security=True;MultipleActiveResultSets=True;App=EntityFramework", tb_Projects.ProjectDatabase);
                        else
                            ConnStrFormat = string.Format("data source={0};initial catalog={1};persist security info=True;user id={2};password={3};multipleactiveresultsets=True;application name=EntityFramework", tb_Projects.Server, tb_Projects.ProjectDatabase, tb_Projects.ProjectUser, tb_Projects.Password);
                        
                        using (SqlConnection connection =new SqlConnection(ConnStrFormat))
                        {
                            connection.Open();
                            if (connection.State.ToString() == "Closed")
                                throw new Exception("Los datos proporcionados son incorrectos.");
                        }

                        tb_Projects.CreationDate = DateTime.Now.Date;
                        db.Tb_Projects.Add(tb_Projects);
                        db.SaveChanges();
                        transaction.Commit();
                        return RedirectToAction("Index");
                    }
                    catch (Exception ex)
                    {
                        transaction.Rollback();
                        MessageBox.Show("Ha ocurrido un error: " + ex.Message);
                    }
                }
            }
            return View(tb_Projects);
        }

        // GET: Project/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tb_Projects tb_Projects = db.Tb_Projects.Find(id);
            if (tb_Projects == null)
            {
                return HttpNotFound();
            }
            return View(tb_Projects);
        }

        // POST: Project/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Project,ProjectName,FileDirectory,LocalConnection,Server,ProjectUser,ProjectDatabase,Password,CreationDate")] Tb_Projects tb_Projects)
        {
            if (ModelState.IsValid)
            {
                using (DbContextTransaction transaction = db.Database.BeginTransaction())
                {
                    try 
                    {
                        db.Entry(tb_Projects).State = EntityState.Modified;
                        string ConnStrFormat = "";
                        if (tb_Projects.LocalConnection.Value)
                            ConnStrFormat = string.Format("data source=./;initial catalog={0};integrated security=True;MultipleActiveResultSets=True;App=EntityFramework", tb_Projects.ProjectDatabase);
                        else
                            ConnStrFormat = string.Format("data source={0};initial catalog={1};persist security info=True;user id={2};password={3};multipleactiveresultsets=True;application name=EntityFramework", tb_Projects.Server, tb_Projects.ProjectDatabase, tb_Projects.ProjectUser, tb_Projects.Password);

                        using (SqlConnection connection = new SqlConnection(ConnStrFormat))
                        {
                            connection.Open();
                            if (connection.State.ToString() == "Closed")
                                throw new Exception("Los datos proporcionados son incorrectos.");
                        }
                        tb_Projects.CreationDate = DateTime.Now.Date;
                        db.SaveChanges();
                        transaction.Commit();
                        return RedirectToAction("Index");
                    }
                    catch(Exception ex)
                    {
                        transaction.Rollback();
                        MessageBox.Show("Error: " + ex.Message);
                    }
                }
            }
            return View(tb_Projects);
        }

        // GET: Project/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tb_Projects tb_Projects = db.Tb_Projects.Find(id);
            if (tb_Projects == null)
            {
                return HttpNotFound();
            }
            return View(tb_Projects);
        }

        // POST: Project/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (ModelState.IsValid)
            {
                using (DbContextTransaction transaction = db.Database.BeginTransaction())
                {
                    try 
                    {
                        List<Tb_Contexts> contexts = new List<Tb_Contexts>();
                        if (contexts.Where(x => x.ID_Project == id).Any())
                        {
                            contexts = db.Tb_Contexts.Where(x => x.ID_Project == id).ToList();
                            db.Tb_Contexts.RemoveRange(contexts);
                            db.SaveChanges();
                        }

                        Tb_Projects tb_Projects = db.Tb_Projects.Find(id);
                        db.Tb_Projects.Remove(tb_Projects);
                        db.SaveChanges();
                        transaction.Commit();
                        return RedirectToAction("Index");
                    }
                    catch (Exception ex)
                    {
                        transaction.Rollback();
                        MessageBox.Show("Error: "+ ex.Message);
                    }
                }
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sensato.GenerateCSharp/Views/Context/Create.cshtml
@model Sensato.GenerateCSharp.Models.Tb_Contexts

@{
    ViewBag.Title = "Create";
}


<h2 style="font-size:35px; color: darkred;">"@ViewBag.CurrentName"</h2>
<h3>Crear Contexto</h3>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Project, new { Value = ViewBag.idProject })

        <div class="form-group">
            @Html.Label(Sensato.GenerateCSharp.GlobalCode.Resources.ContextName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContextName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContextName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(Sensato.GenerateCSharp.GlobalCode.Resources.BackToListC, "Index", new { ID_Project = ViewBag.idProject })
    <hr />
    <button type="button" class="btn-link" onclick="GoToIndex()">@Sensato.GenerateCSharp.GlobalCode.Resources.BackToListP</button>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
        $(document).ready(function () {

        });

        function GoToIndex() {
            window.location.href = "@Url.Action("Index", "Project")";
        }
</script>
}

Sensato.GenerateCSharp/Views/Context/Delete.cshtml
@model Sensato.GenerateCSharp.Models.Tb_Contexts

@{
    ViewBag.Title = "Delete";
}


<h2 style="font-size:35px; color:darkred;">"@ViewBag.CurrentName"</h2>
<h3>Eliminar</h3>
<h4>¿Está seguro que desea eliminar el Contexto?</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName(Sensato.GenerateCSharp.GlobalCode.Resources.ContextName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContextName)
        </dd>

        <dt>
            @Html.DisplayName(Sensato.GenerateCSharp.GlobalCode.Resources.CreationDate)
        </dt>

        <dd>
            @String.Format("{0:dd/MM/yyyy}", Model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayName("Proyecto Raíz")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tb_Projects.ProjectName)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-danger" /> |
            @Html.ActionLink(Sensato.GenerateCSharp.GlobalCode.Resources.BackToListC, "Index", new { ViewBag.id_Project })
            <hr />
            <button type="button" class="btn-link" onclick="GoToIndex()">@Sensato.GenerateCSharp.GlobalCode.Resources.BackToListP</button>
        </div>
    }
</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {

        });

        function GoToIndex() {
            window.location.href = "@Url.Action("Index", "Project")";
        }
    </script>
    }

Sensato.GenerateCSharp/Views/Context/Edit.cshtml
@model Sensato.GenerateCSharp.Models.Tb_Contexts

@{
    ViewBag.Title = "Edit";
}


<h2 style="font-size: 35px; color:darkred;">"@ViewBag.CurrentName"</h2>
<h3>Editar</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID_Context)

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID_Project, new { Value = ViewBag.id_Project })

    <div class="form-group">
        @Html.Label(Sensato.GenerateCSharp.GlobalCode.Resources.ContextName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContextName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ContextName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink(Sensato.GenerateCSharp.GlobalCode.Resources.BackToListC, "Index", new { ViewBag.id_Project })
    <hr />
    <button type="button" class="btn-link" onclick="GoToIndex()">@Sensato.GenerateCSharp.GlobalCode.Resources.BackToListP</button>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    
<script type="text/javascript">
        $(document).ready(function () {

        });

        function GoToIndex() {
            window.location.href = "@Url.Action("Index", "Project")";
        }
</script>
}

Sensato.GenerateCSharp/Views/Context/Index.cshtml
@model IEnumerable<Sensato.GenerateCSharp.Models.Tb_Contexts>

@{
    ViewBag.Title = "Index";
}

<h2 style="font-size: 35px; color:darkred;">"@ViewBag.CurrentName"</h2>
<h3>Lista de Contextos</h3>

<p>
    @Html.ActionLink(Sensato.GenerateCSharp.GlobalCode.Resources.CreateNew, "Create", new { ID_Project = ViewBag.CurrentProject }, new { @class = "btn btn-warning" })
</p>
<table class="table table-bordered table-condensed">
    <tr class="bg-info">
        <th>
            @Html.DisplayName(Sensato.GenerateCSharp.GlobalCode.Resources.ContextName)
        </th>
        <th>
            @Html.DisplayName("Proyecto Raíz")
        </th>
        <th>
            @Html.DisplayName(Sensato.GenerateCSharp.GlobalCode.Resources.CreationDate)
        </th>
        <th>
            Acciones
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ContextName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tb_Projects.ProjectName)
            </td>
            <td>
                @String.Format("{0:dd/MM/yyyy}", item.CreationDate)
            </td>
            <td>
                @Html.ActionLink(Sensato.GenerateCSharp.GlobalCode.Resources.Edit, "Edit", new { id = item.ID_Context }) |
                @Html.ActionLink(Sensato.GenerateCSharp.GlobalCode.Resources.Delete, "Delete", new { id = item.ID_Context }) |
                <button type="button" class="btn btn-link" onclick="AddObjects(@item.ID_Context, @item.ID_Project)">Ver Objetos</button>
            </td>
        </tr>
    }

</table>

<button type="button" class="btn-link" onclick="GoToIndex()">@Sensato.GenerateCSharp.GlobalCode.Resources.BackToListP</button>

@section scripts
    {
    <script type="text/javascript">
        $(document).ready(function () {
        });

        function GoToIndex() {
            window.location.href = "@Url.Action("Index", "Project")";
        }

        function AddObjects(idContext, idProject) {
            window.location.href = "@Url.Action("Index", "Object")?idContext=" + idContext + '&idProject=' + idProject;
        }

    </script>
    }